In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout,GRU
from keras.optimizers import Adam, RMSprop
from keras.losses import binary_crossentropy
from keras.metrics import accuracy

In [21]:
data_df = pd.read_csv('../../preprocessed_data_final.csv')
data_df

,날짜,지수종가,종가이동평균_5,거래량,거래량이동평균_5,자본금,전체종목수,상승종목수,하락종목수,보합종목수,...,운수장비,서비스업,snp500,nasdaq,shanghai,COMP,NEG,NEUT,None,POS
0,2001-01-08,586.65,553.580,558645100,19.873264,84853590,902,533,278,45,...,9.22,11.03,0.77,-0.49,-1.09,0.005082,0.360881,0.041947,0.000518,0.591572
1,2001-01-09,589.92,567.374,558967700,20.016030,84881174,902,527,282,49,...,9.34,11.32,-0.27,1.89,-0.04,0.011277,0.478814,0.085582,0.016079,0.408248
2,2001-01-10,560.81,575.250,642378200,20.137292,84891369,902,137,698,23,...,8.64,11.08,1.76,3.39,1.16,0.000000,0.555556,0.055556,0.000000,0.388889
3,2001-01-11,561.79,576.004,518788600,20.163623,84906240,902,574,242,43,...,8.41,11.29,0.10,4.61,-0.30,0.007067,0.381705,0.140920,0.045477,0.424830
4,2001-01-12,587.87,577.408,713787700,20.209960,84909240,902,494,298,68,...,8.95,11.83,-0.19,-0.53,-0.68,0.003084,0.369053,0.021311,0.000881,0.605672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4440,2018-12-21,2061.49,2066.730,311388800,19.819547,107914395,900,381,445,70,...,53.68,25.44,-2.62,-2.99,-0.79,0.022321,0.358543,0.064166,0.037088,0.517881
4441,2018-12-24,2055.01,2063.514,285275000,19.737655,107972455,900,285,538,71,...,53.59,25.35,-2.64,-2.21,0.43,0.018742,0.354360,0.057304,0.048192,0.521403
4442,2018-12-26,2028.01,2056.694,321499300,19.678019,108073277,900,128,724,44,...,52.15,24.78,5.05,5.84,-0.26,0.020903,0.346296,0.063338,0.043228,0.526235
4443,2018-12-27,2028.44,2046.614,398021300,19.666131,108148532,901,521,331,45,...,52.35,25.16,0.77,0.38,-0.61,0.016228,0.354153,0.059219,0.045312,0.525088
4444,2018-12-28,2041.04,2042.798,352677700,19.625970,108148442,901,577,253,67,...,52.63,25.15,-0.13,0.08,0.44,0.024354,0.363524,0.058933,0.041967,0.511221

In [22]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4445 entries, 0 to 4444
Data columns (total 34 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   날짜         4445 non-null   object
 1   지수종가       4445 non-null   float64
 2   종가이동평균_5   4445 non-null   float64
 3   거래량        4445 non-null   int64
 4   거래량이동평균_5  4445 non-null   float64
 5   자본금        4445 non-null   int64
 6   전체종목수      4445 non-null   int64
 7   상승종목수      4445 non-null   int64
 8   하락종목수      4445 non-null   int64
 9   보합종목수      4445 non-null   int64
 10  상한종목수      4445 non-null   int64
 11  하한종목수      4445 non-null   int64
 12  연중최고가종목수   4445 non-null   int64
 13  연중최저가종목수   4445 non-null   int64
 14  52주신고가종목수  4445 non-null   int64
 15  52주신저가종목수  4445 non-null   int64
 16  변동률        4445 non-null   float64
 17  금괴(일간)     4445 non-null   float64
 18  국고채권(10년)  4445 non-null   float64
 19  원유 WTI     4445 non-null   float64
 20  USD        4445 non-null   float64
 21  코스피 200    4445 non-null   float64
 22  제조업        4445 non-null   float64
 23  전기전자       4445 non-null   float64
 24  운수장비       4445 non-null   float64
 25  서비스업       4445 non-null   float64
 26  snp500     4445 non-null   float64
 27  nasdaq     4445 non-null   float64
 28  shanghai   4445 non-null   float64
 29  COMP       4445 non-null   float64
 30  NEG        4445 non-null   float64
 31  NEUT       4445 non-null   float64
 32  None       4445 non-null   float64
 33  POS        4445 non-null   float64
dtypes: float64(21), int64(12), object(1)
memory usage: 1.2+ MB

In [23]:
data_df.describe()

,지수종가,종가이동평균_5,거래량,거래량이동평균_5,자본금,전체종목수,상승종목수,하락종목수,보합종목수,상한종목수,...,운수장비,서비스업,snp500,nasdaq,shanghai,COMP,NEG,NEUT,None,POS
count,4445.000000,4445.000000,4.445000e+03,4445.000000,4.445000e+03,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,...,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000
mean,1566.345773,1565.679890,4.218820e+08,19.795263,9.360336e+07,893.698538,383.814398,408.103712,70.534083,9.534758,...,11.993291,16.353618,0.020333,0.028823,0.011417,0.019328,0.377203,0.062947,0.041461,0.499060
std,564.712688,564.783055,1.889785e+08,0.346692,9.213751e+06,30.065657,129.055575,133.096115,17.167047,10.934980,...,5.949642,8.228201,1.183392,1.416666,1.552455,0.007372,0.043241,0.018128,0.024389,0.045411
min,468.760000,474.372000,1.363290e+08,18.900436,7.858320e+07,832.000000,15.000000,46.000000,2.000000,0.000000,...,5.300000,1.590000,-9.840000,-9.140000,-8.840000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1016.820000,1010.090000,3.056365e+08,19.567431,8.409615e+07,878.000000,301.000000,317.000000,60.000000,3.000000,...,8.700000,11.580000,-0.430000,-0.560000,-0.650000,0.017433,0.363337,0.058086,0.038783,0.485093
50%,1766.710000,1763.866000,3.813070e+08,19.761609,9.764014e+07,893.000000,385.000000,396.000000,72.000000,7.000000,...,10.040000,14.680000,0.040000,0.050000,0.000000,0.019940,0.375458,0.061697,0.042522,0.499511
75%,1996.980000,1996.006000,4.864097e+08,19.992901,1.004792e+08,919.000000,468.000000,490.000000,83.000000,13.000000,...,13.180000,20.440000,0.540000,0.690000,0.710000,0.022094,0.388546,0.065362,0.045991,0.512412
max,2598.190000,2575.138000,2.379294e+09,21.391700,1.106207e+08,1520.000000,955.000000,865.000000,122.000000,376.000000,...,54.520000,40.890000,14.520000,11.810000,9.860000,0.166667,0.798948,0.424242,1.000000,1.000000

In [24]:
data_df = data_df.drop(['날짜','변동률','연중최고가종목수','연중최저가종목수'], axis=1, inplace=False)

In [25]:
data_df

,지수종가,종가이동평균_5,거래량,거래량이동평균_5,자본금,전체종목수,상승종목수,하락종목수,보합종목수,상한종목수,...,운수장비,서비스업,snp500,nasdaq,shanghai,COMP,NEG,NEUT,None,POS
0,586.65,553.580,558645100,19.873264,84853590,902,533,278,45,72,...,9.22,11.03,0.77,-0.49,-1.09,0.005082,0.360881,0.041947,0.000518,0.591572
1,589.92,567.374,558967700,20.016030,84881174,902,527,282,49,64,...,9.34,11.32,-0.27,1.89,-0.04,0.011277,0.478814,0.085582,0.016079,0.408248
2,560.81,575.250,642378200,20.137292,84891369,902,137,698,23,36,...,8.64,11.08,1.76,3.39,1.16,0.000000,0.555556,0.055556,0.000000,0.388889
3,561.79,576.004,518788600,20.163623,84906240,902,574,242,43,87,...,8.41,11.29,0.10,4.61,-0.30,0.007067,0.381705,0.140920,0.045477,0.424830
4,587.87,577.408,713787700,20.209960,84909240,902,494,298,68,27,...,8.95,11.83,-0.19,-0.53,-0.68,0.003084,0.369053,0.021311,0.000881,0.605672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4440,2061.49,2066.730,311388800,19.819547,107914395,900,381,445,70,0,...,53.68,25.44,-2.62,-2.99,-0.79,0.022321,0.358543,0.064166,0.037088,0.517881
4441,2055.01,2063.514,285275000,19.737655,107972455,900,285,538,71,1,...,53.59,25.35,-2.64,-2.21,0.43,0.018742,0.354360,0.057304,0.048192,0.521403
4442,2028.01,2056.694,321499300,19.678019,108073277,900,128,724,44,0,...,52.15,24.78,5.05,5.84,-0.26,0.020903,0.346296,0.063338,0.043228,0.526235
4443,2028.44,2046.614,398021300,19.666131,108148532,901,521,331,45,1,...,52.35,25.16,0.77,0.38,-0.61,0.016228,0.354153,0.059219,0.045312,0.525088
4444,2041.04,2042.798,352677700,19.625970,108148442,901,577,253,67,0,...,52.63,25.15,-0.13,0.08,0.44,0.024354,0.363524,0.058933,0.041967,0.511221

In [26]:
def normalize_data(df):
    scaler = MinMaxScaler()
    for i, column in enumerate(data_df.columns):
        df[data_df.columns[i]] = scaler.fit_transform(df[data_df.columns[i]].values.reshape(-1,1))
    return df

In [27]:
normalized_data_df = normalize_data(data_df)
normalized_data_df.describe()

,지수종가,종가이동평균_5,거래량,거래량이동평균_5,자본금,전체종목수,상승종목수,하락종목수,보합종목수,상한종목수,...,운수장비,서비스업,snp500,nasdaq,shanghai,COMP,NEG,NEUT,None,POS
count,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,...,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000,4445.000000
mean,0.515436,0.519481,0.127310,0.359186,0.468830,0.089678,0.392356,0.442129,0.571117,0.025358,...,0.135987,0.375665,0.404776,0.437653,0.473338,0.115969,0.472125,0.148376,0.041461,0.499060
std,0.265194,0.268846,0.084254,0.139163,0.287593,0.043700,0.137293,0.162511,0.143059,0.029082,...,0.120879,0.209369,0.048579,0.067621,0.083019,0.044230,0.054123,0.042730,0.024389,0.045411
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.257374,0.255011,0.075484,0.267734,0.172078,0.066860,0.304255,0.330891,0.483333,0.007979,...,0.069078,0.254198,0.386289,0.409547,0.437968,0.104597,0.454770,0.136916,0.038783,0.485093
50%,0.609529,0.613821,0.109221,0.345677,0.594832,0.088663,0.393617,0.427350,0.583333,0.018617,...,0.096302,0.333079,0.405583,0.438663,0.472727,0.119640,0.469941,0.145428,0.042522,0.499511
75%,0.717666,0.724323,0.156079,0.438518,0.683448,0.126453,0.481915,0.542125,0.675000,0.034574,...,0.160098,0.479644,0.426108,0.469212,0.510695,0.132564,0.486322,0.154067,0.045991,0.512412
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [28]:
def generator(data, lookback=10, delay=5, min_index=0, max_index=None):
    data = data.values #DataFrame을 넘파이로 바꾸기
    max_index = len(data) - delay -1 #4439
    i = min_index + lookback #index10부터 
    samples = np.zeros((len(range(max_index-i+1)), lookback, data.shape[-1])) #(4430, 10, 33)
    targets = np.zeros((len(range(max_index-i+1)),)) #(4430,)
    while i <= max_index:
        indices = range(i-lookback, i)
        samples[i-lookback] = data[indices]
        if data[i+delay][0] - data[i][0] >= 0:
            targets[i-lookback] = 1
        else:
            targets[i-lookback] = 0
        i+=1
    return samples, targets

In [29]:
samples, targets = generator(normalized_data_df, min_index=0, max_index=3500)

In [30]:
print(samples.shape)
print(targets.shape)

(4430, 10, 30)
(4430,)

In [31]:
def split_data(sample, target, train_size_percentage=90, shuffle=True):
    if shuffle is True:
        index = np.arange(sample.shape[0])
        np.random.shuffle(index)
        sample = sample[index]
        target = target[index]
    train_size = train_size_percentage*sample.shape[0]//100
    test_size = sample.shape[0] - train_size
    
    x_train = sample[:train_size]
    y_train = target[:train_size]
    x_test = sample[train_size:]
    y_test = target[train_size:]
    
    return x_train, y_train, x_test, y_test

In [32]:
x_train, y_train, x_test, y_test = split_data(samples, targets)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3987, 10, 30)
(3987,)
(443, 10, 30)
(443,)

In [33]:
#d= 0.3 #0.1~0.5
model = Sequential()
model.add(GRU(32,input_shape=(x_train.shape[1], x_train.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(64, return_sequences=True))
model.add(Dropout(0.5))
model.add(GRU(64))
model.add(Dense(32, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam')

model.fit(x_train,y_train,batch_size=64,epochs=100,verbose=1,validation_split=0.2)

Train on 3189 samples, validate on 798 samples
Epoch 1/100
3189/3189 [==============================] - 5s 2ms/step - loss: 0.6868 - val_loss: 0.6792
Epoch 2/100
3189/3189 [==============================] - 2s 572us/step - loss: 0.6813 - val_loss: 0.6762
Epoch 3/100
3189/3189 [==============================] - 2s 579us/step - loss: 0.6805 - val_loss: 0.6700
Epoch 4/100
3189/3189 [==============================] - 2s 549us/step - loss: 0.6810 - val_loss: 0.6696
Epoch 5/100
3189/3189 [==============================] - 2s 547us/step - loss: 0.6822 - val_loss: 0.6702
Epoch 6/100
3189/3189 [==============================] - 2s 523us/step - loss: 0.6779 - val_loss: 0.6700
Epoch 7/100
3189/3189 [==============================] - 2s 508us/step - loss: 0.6745 - val_loss: 0.6664
Epoch 8/100
3189/3189 [==============================] - 2s 541us/step - loss: 0.6774 - val_loss: 0.6672
Epoch 9/100
3189/3189 [==============================] - 2s 561us/step - loss: 0.6747 - val_loss: 0.6620
Epoch 10/100
3189/3189 [==============================] - 2s 534us/step - loss: 0.6731 - val_loss: 0.6673
Epoch 11/100
3189/3189 [==============================] - 2s 644us/step - loss: 0.6725 - val_loss: 0.6624
Epoch 12/100
3189/3189 [==============================] - 2s 547us/step - loss: 0.6735 - val_loss: 0.6629
Epoch 13/100
3189/3189 [==============================] - 2s 609us/step - loss: 0.6720 - val_loss: 0.6631
Epoch 14/100
3189/3189 [==============================] - 2s 583us/step - loss: 0.6701 - val_loss: 0.6628
Epoch 15/100
3189/3189 [==============================] - 2s 564us/step - loss: 0.6706 - val_loss: 0.6592
Epoch 16/100
3189/3189 [==============================] - 2s 551us/step - loss: 0.6715 - val_loss: 0.6618
Epoch 17/100
3189/3189 [==============================] - 2s 566us/step - loss: 0.6712 - val_loss: 0.6638
Epoch 18/100
3189/3189 [==============================] - 2s 590us/step - loss: 0.6674 - val_loss: 0.6618
Epoch 19/100
3189/3189 [==============================] - 2s 574us/step - loss: 0.6701 - val_loss: 0.6603
Epoch 20/100
3189/3189 [==============================] - 2s 505us/step - loss: 0.6674 - val_loss: 0.6559
Epoch 21/100
3189/3189 [==============================] - 2s 579us/step - loss: 0.6635 - val_loss: 0.6578
Epoch 22/100
3189/3189 [==============================] - 2s 529us/step - loss: 0.6670 - val_loss: 0.6621
Epoch 23/100
3189/3189 [==============================] - ETA: 0s - loss: 0.669 - 2s 539us/step - loss: 0.6704 - val_loss: 0.6575
Epoch 24/100
3189/3189 [==============================] - 2s 518us/step - loss: 0.6743 - val_loss: 0.6590
Epoch 25/100
3189/3189 [==============================] - 2s 573us/step - loss: 0.6626 - val_loss: 0.6561
Epoch 26/100
3189/3189 [==============================] - 2s 553us/step - loss: 0.6632 - val_loss: 0.6558
Epoch 27/100
3189/3189 [==============================] - 2s 566us/step - loss: 0.6584 - val_loss: 0.6688
Epoch 28/100
3189/3189 [==============================] - 2s 528us/step - loss: 0.6583 - val_loss: 0.6573
Epoch 29/100
3189/3189 [==============================] - 2s 559us/step - loss: 0.6597 - val_loss: 0.6563
Epoch 30/100
3189/3189 [==============================] - 2s 525us/step - loss: 0.6602 - val_loss: 0.6554
Epoch 31/100
3189/3189 [==============================] - 2s 758us/step - loss: 0.6566 - val_loss: 0.6530
Epoch 32/100
3189/3189 [==============================] - 2s 555us/step - loss: 0.6539 - val_loss: 0.6523
Epoch 33/100
3189/3189 [==============================] - 2s 645us/step - loss: 0.6558 - val_loss: 0.6541
Epoch 34/100
3189/3189 [==============================] - 2s 587us/step - loss: 0.6522 - val_loss: 0.6584
Epoch 35/100
3189/3189 [==============================] - 2s 596us/step - loss: 0.6515 - val_loss: 0.6510
Epoch 36/100
3189/3189 [==============================] - 2s 565us/step - loss: 0.6519 - val_loss: 0.6532
Epoch 37/100
3189/3189 [==============================] - 2s 517us/step - loss: 0.6526 - val_loss: 0.6582
Epoch 38/100
3189/3189 [==============================] - 2s 565us/step - loss: 0.6468 - val_loss: 0.6486
Epoch 39/100
3189/3189 [==============================] - 2s 510us/step - loss: 0.6436 - val_loss: 0.6453
Epoch 40/100
3189/3189 [==============================] - 2s 555us/step - loss: 0.6483 - val_loss: 0.6527
Epoch 41/100
3189/3189 [==============================] - 2s 526us/step - loss: 0.6408 - val_loss: 0.6517
Epoch 42/100
3189/3189 [==============================] - 2s 565us/step - loss: 0.6425 - val_loss: 0.6610
Epoch 43/100
3189/3189 [==============================] - 2s 541us/step - loss: 0.6449 - val_loss: 0.6489
Epoch 44/100
3189/3189 [==============================] - 2s 616us/step - loss: 0.6398 - val_loss: 0.6490
Epoch 45/100
3189/3189 [==============================] - 2s 538us/step - loss: 0.6365 - val_loss: 0.6510
Epoch 46/100
3189/3189 [==============================] - 2s 565us/step - loss: 0.6341 - val_loss: 0.6650
Epoch 47/100
3189/3189 [==============================] - 2s 584us/step - loss: 0.6360 - val_loss: 0.6506
Epoch 48/100
3189/3189 [==============================] - 2s 565us/step - loss: 0.6389 - val_loss: 0.6597
Epoch 49/100
3189/3189 [==============================] - 2s 564us/step - loss: 0.6344 - val_loss: 0.6533
Epoch 50/100
3189/3189 [==============================] - 2s 562us/step - loss: 0.6289 - val_loss: 0.6564
Epoch 51/100
3189/3189 [==============================] - 2s 516us/step - loss: 0.6233 - val_loss: 0.6511
Epoch 52/100
3189/3189 [==============================] - 2s 547us/step - loss: 0.6206 - val_loss: 0.6648
Epoch 53/100
3189/3189 [==============================] - 2s 538us/step - loss: 0.6297 - val_loss: 0.6631
Epoch 54/100
3189/3189 [==============================] - 2s 541us/step - loss: 0.6186 - val_loss: 0.6498
Epoch 55/100
3189/3189 [==============================] - 2s 510us/step - loss: 0.6225 - val_loss: 0.6436
Epoch 56/100
3189/3189 [==============================] - 2s 502us/step - loss: 0.6150 - val_loss: 0.6594
Epoch 57/100
3189/3189 [==============================] - 2s 520us/step - loss: 0.6229 - val_loss: 0.6432
Epoch 58/100
3189/3189 [==============================] - 2s 557us/step - loss: 0.6120 - val_loss: 0.6419
Epoch 59/100
3189/3189 [==============================] - 2s 510us/step - loss: 0.6077 - val_loss: 0.6496
Epoch 60/100
3189/3189 [==============================] - 2s 572us/step - loss: 0.6157 - val_loss: 0.6321
Epoch 61/100
3189/3189 [==============================] - 2s 532us/step - loss: 0.6007 - val_loss: 0.6477
Epoch 62/100
3189/3189 [==============================] - 2s 573us/step - loss: 0.5948 - val_loss: 0.6538
Epoch 63/100
3189/3189 [==============================] - 2s 515us/step - loss: 0.5975 - val_loss: 0.6286
Epoch 64/100
3189/3189 [==============================] - 2s 554us/step - loss: 0.5975 - val_loss: 0.6383
Epoch 65/100
3189/3189 [==============================] - 2s 534us/step - loss: 0.5947 - val_loss: 0.6402
Epoch 66/100
3189/3189 [==============================] - 2s 510us/step - loss: 0.5949 - val_loss: 0.6353
Epoch 67/100
3189/3189 [==============================] - 2s 523us/step - loss: 0.5927 - val_loss: 0.6375
Epoch 68/100
3189/3189 [==============================] - 2s 546us/step - loss: 0.5882 - val_loss: 0.6344
Epoch 69/100
3189/3189 [==============================] - 2s 525us/step - loss: 0.5871 - val_loss: 0.6352
Epoch 70/100
3189/3189 [==============================] - 2s 520us/step - loss: 0.5876 - val_loss: 0.6458 ETA: 0s - l
Epoch 71/100
3189/3189 [==============================] - 2s 516us/step - loss: 0.5830 - val_loss: 0.6304
Epoch 72/100
3189/3189 [==============================] - 2s 534us/step - loss: 0.5809 - val_loss: 0.6374
Epoch 73/100
3189/3189 [==============================] - 2s 546us/step - loss: 0.5756 - val_loss: 0.6272
Epoch 74/100
3189/3189 [==============================] - 2s 519us/step - loss: 0.5714 - val_loss: 0.6321
Epoch 75/100
3189/3189 [==============================] - 2s 536us/step - loss: 0.5754 - val_loss: 0.6347
Epoch 76/100
3189/3189 [==============================] - 2s 548us/step - loss: 0.5709 - val_loss: 0.6686
Epoch 77/100
3189/3189 [==============================] - 2s 564us/step - loss: 0.5642 - val_loss: 0.6475
Epoch 78/100
3189/3189 [==============================] - 2s 533us/step - loss: 0.5695 - val_loss: 0.6249
Epoch 79/100
3189/3189 [==============================] - 2s 582us/step - loss: 0.5606 - val_loss: 0.6628
Epoch 80/100
3189/3189 [==============================] - 2s 546us/step - loss: 0.5606 - val_loss: 0.6211
Epoch 81/100
3189/3189 [==============================] - 2s 561us/step - loss: 0.5581 - val_loss: 0.6268
Epoch 82/100
3189/3189 [==============================] - 2s 538us/step - loss: 0.5401 - val_loss: 0.6419
Epoch 83/100
3189/3189 [==============================] - 2s 561us/step - loss: 0.5558 - val_loss: 0.6450
Epoch 84/100
3189/3189 [==============================] - 2s 542us/step - loss: 0.5598 - val_loss: 0.6303
Epoch 85/100
3189/3189 [==============================] - 2s 548us/step - loss: 0.5566 - val_loss: 0.6291
Epoch 86/100
3189/3189 [==============================] - 2s 547us/step - loss: 0.5537 - val_loss: 0.6382
Epoch 87/100
3189/3189 [==============================] - 2s 532us/step - loss: 0.5731 - val_loss: 0.6530
Epoch 88/100
3189/3189 [==============================] - 2s 534us/step - loss: 0.5393 - val_loss: 0.6466
Epoch 89/100
3189/3189 [==============================] - 2s 525us/step - loss: 0.5346 - val_loss: 0.6242
Epoch 90/100
3189/3189 [==============================] - 2s 537us/step - loss: 0.5355 - val_loss: 0.6483
Epoch 91/100
3189/3189 [==============================] - 2s 554us/step - loss: 0.5542 - val_loss: 0.6536
Epoch 92/100
3189/3189 [==============================] - 2s 514us/step - loss: 0.5281 - val_loss: 0.6430
Epoch 93/100
3189/3189 [==============================] - 2s 558us/step - loss: 0.5198 - val_loss: 0.6210
Epoch 94/100
3189/3189 [==============================] - 2s 526us/step - loss: 0.5348 - val_loss: 0.6388
Epoch 95/100
3189/3189 [==============================] - 2s 558us/step - loss: 0.5239 - val_loss: 0.6324
Epoch 96/100
3189/3189 [==============================] - 2s 534us/step - loss: 0.5298 - val_loss: 0.6437
Epoch 97/100
3189/3189 [==============================] - 2s 585us/step - loss: 0.5198 - val_loss: 0.6289
Epoch 98/100
3189/3189 [==============================] - 2s 529us/step - loss: 0.5209 - val_loss: 0.6425
Epoch 99/100
3189/3189 [==============================] - 2s 584us/step - loss: 0.5177 - val_loss: 0.6267
Epoch 100/100
3189/3189 [==============================] - 2s 537us/step - loss: 0.5151 - val_loss: 0.6422

In [34]:
def eval_acc(models, x_test_data, y_test_data, threshold=0.5):
    scores = models.predict(x_test_data)
    classified_scores=[]
    for score in scores:
        if score >= threshold:
            classified_scores.append(1)
        else:
            classified_scores.append(0)
    
    acc=0
    for i, classified_score in enumerate(classified_scores):
        if classified_score== y_test_data[i]:
            acc+=1
    accuracy_score = acc/len(y_test_data)*100
    
    return str(accuracy_score) + ' %'

In [35]:
eval_acc(model, x_test, y_test)

'60.496613995485326 %'

In [36]:
scores = model.predict(x_test)
classified_scores=[]
for score in scores:
    if score >= 0.5:
        classified_scores.append(1)
    else:
        classified_scores.append(0)

In [37]:
from sklearn.metrics import f1_score

f1_score(y_test, classified_scores)

0.6835443037974683